### PR TITLE
Remove try...catch

### PR DESCRIPTION
**Pull request by domoritz**
So users actually see the errors

### CODE REVIEW

**Comment by sachinchoolur** [comment]
Hey @domoritz ,
I know this PR is really old and sorry for not responding in time.  Instead of removing the try-catch, can we console the real error? So it does not break anything else in the application.
something like this. 

``` js 
catch (err) {
  console.error('lightGallery has not initiated properly', err);
}
```

Would you be able to update the PR

**Comment by domoritz** [comment]
Done in https://github.com/sachinchoolur/lightgallery.js/pull/181

**Comment by sachinchoolur** [comment]
Merged https://github.com/sachinchoolur/lightgallery.js/pull/181

**Comment by sachinchoolur** [comment]
Hey @domoritz,
Can you please make the changes in jQuery lightGallery as well? - https://github.com/sachinchoolur/lightGallery/pull/871

**Pull request closed without merging**
