### PR TITLE
Fix a spelling mistake

### PR DESCRIPTION
**Pull request by Maistho**
'toogle' should be spelled as 'toggle'

### CODE REVIEW

**Comment by Maistho** [comment]
Let me know if there's anything wrong with my approach here (if you'd like to build the minified files yourself or similar), and I'll update the PR.

There is also a matching documentation change at #18

**Comment by sachinchoolur** [comment]
Hi @Maistho,
Thanks for the PR. Javascript changes of lightgallery plugins should be updated on the respective plugin repository. 
Could you please submit a PR on [thumbnail pugin](https://github.com/sachinchoolur/lg-thumbnail.js) repository?
Sorry for not being clear about this on docs.  I will update the guidelines.

CSS and SCSS changes should be made on ligtgallery.js repository.

Just update the files in the src folder. I will create the minified files myself.

**Comment by Maistho** [comment]
@sachinchoolur Okay, I wasn't aware that there was multiple plugins! I'll update this PR and submit a new one.

**Comment by Maistho** [comment]
I'll open a new PR

**Pull request closed without merging**
